# Generated by Django 5.1.6 on 2025-02-22 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="publish_date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="source",
        ),
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 22, 13, 28, 4, 893028, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
