# Generated by Django 5.1.6 on 2025-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_article_publish_date_remove_article_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
