# Generated by Django 5.1.6 on 2025-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_article_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image_path",
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
