# Generated by Django 5.1.6 on 2025-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_article_image_path_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
