# Generated by Django 5.1.6 on 2025-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_article_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="date",
        ),
        migrations.AddField(
            model_name="article",
            name="articleId",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="createdAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="longerSummary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="popularityScore",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
