# Generated by Django 5.1.6 on 2025-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_article_date_article_articleid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="priority",
            field=models.TextField(blank=True, null=True),
        ),
    ]
